config/routes.rb
Rails.application.routes.draw do
  resources :childcompanies
  resources :companies

end

app/models/childcompany.rb
class Childcompany < ActiveRecord::Base
    belongs_to :company
end

app/models/company.rb
class Company < ActiveRecord::Base
    has_many :childcompany
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/childcompanies_controller.rb
class ChildcompaniesController < ApplicationController
  before_action :set_childcompany, only: [:show, :edit, :update, :destroy]

  # GET /childcompanies
  # GET /childcompanies.json
  def index
    @childcompanies = Childcompany.all
  end

  # GET /childcompanies/1
  # GET /childcompanies/1.json
  def show
  end

  # GET /childcompanies/new
  def new
    @childcompany = Childcompany.new
  end

  # GET /childcompanies/1/edit
  def edit
  end

  # POST /childcompanies
  # POST /childcompanies.json
  def create
    @childcompany = Childcompany.new(childcompany_params)

    respond_to do |format|
      if @childcompany.save
        format.html { redirect_to @childcompany, notice: 'Childcompany was successfully created.' }
        format.json { render :show, status: :created, location: @childcompany }
      else
        format.html { render :new }
        format.json { render json: @childcompany.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /childcompanies/1
  # PATCH/PUT /childcompanies/1.json
  def update
    respond_to do |format|
      if @childcompany.update(childcompany_params)
        format.html { redirect_to @childcompany, notice: 'Childcompany was successfully updated.' }
        format.json { render :show, status: :ok, location: @childcompany }
      else
        format.html { render :edit }
        format.json { render json: @childcompany.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /childcompanies/1
  # DELETE /childcompanies/1.json
  def destroy
    @childcompany.destroy
    respond_to do |format|
      format.html { redirect_to childcompanies_url, notice: 'Childcompany was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_childcompany
      @childcompany = Childcompany.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def childcompany_params
      params.require(:childcompany).permit(:cost1, :cost2, :company)
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :cost1, :cost2)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/childcompanies_helper.rb
module ChildcompaniesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/childcompanies/_form.html.erb
<%= form_for(@childcompany) do |f| %>
  <% if @childcompany.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@childcompany.errors.count, "error") %> prohibited this childcompany from being saved:</h2>

      <ul>
      <% @childcompany.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cost1 %><br>
    <%= f.text_field :cost1 %>
  </div>
  <div class="field">
    <%= f.label :cost2 %><br>
    <%= f.text_field :cost2 %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.number_field :company %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/childcompanies/edit.html.erb
<h1>Editing Childcompany</h1>

<%= render 'form' %>

<%= link_to 'Show', @childcompany %> |
<%= link_to 'Back', childcompanies_path %>

app/views/childcompanies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Childcompanies</h1>

<table>
  <thead>
    <tr>
      <th>Cost1</th>
      <th>Cost2</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @childcompanies.each do |childcompany| %>
      <tr>
        <td><%= childcompany.cost1 %></td>
        <td><%= childcompany.cost2 %></td>
        <td><%= childcompany.company %></td>
        <td><%= link_to 'Show', childcompany %></td>
        <td><%= link_to 'Edit', edit_childcompany_path(childcompany) %></td>
        <td><%= link_to 'Destroy', childcompany, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Childcompany', new_childcompany_path %>

app/views/childcompanies/new.html.erb
<h1>New Childcompany</h1>

<%= render 'form' %>

<%= link_to 'Back', childcompanies_path %>

app/views/childcompanies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cost1:</strong>
  <%= @childcompany.cost1 %>
</p>

<p>
  <strong>Cost2:</strong>
  <%= @childcompany.cost2 %>
</p>

<p>
  <strong>Company:</strong>
  <%= @childcompany.company %>
</p>

<%= link_to 'Edit', edit_childcompany_path(@childcompany) %> |
<%= link_to 'Back', childcompanies_path %>

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cost1 %><br>
    <%= f.text_field :cost1 %>
  </div>
  <div class="field">
    <%= f.label :cost2 %><br>
    <%= f.text_field :cost2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cost1</th>
      <th>Cost2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.cost1 %></td>
        <td><%= company.cost2 %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Cost1:</strong>
  <%= @company.cost1 %>
</p>

<p>
  <strong>Cost2:</strong>
  <%= @company.cost2 %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>